substitutions:
  device_name: corridor_motion_witty

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp12e
  # board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 20min

# Enable logging
logger:
  # level: DEBUG
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret api_ota_pass
  reboot_timeout: 20min

ota:
  password: !secret api_ota_pass

web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: output_led_red
    pin: GPIO15
  - platform: esp8266_pwm
    id: output_led_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_led_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO2
    inverted: True

# http://www.schatenseite.de/wp-content/uploads/2016/04/160422_witty_cloud_01-1.jpg

binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: '${device_name} motion'
    id: corridor_motion_sensor
    device_class: motion

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: '${device_name} Button'
    filters:
      - invert:

sensor:
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s

  - platform: adc
    pin: A0
    name: '${device_name} Illuminance'
    unit_of_measurement: lux
    update_interval: 10s
    filters:
      - lambda: return (x * 3.3 / 10000.0) * 2000000.0;
  - platform: adc
    pin: VCC
    name: '${device_name} VCC Voltage'

light:
  - platform: rgb
    id: corridor_rgb
    name: "Corridor RGB"
    red: output_led_red
    green: output_led_green
    blue: output_led_blue

  - platform: monochromatic
    name: '${device_name} blue light'
    id: corridor_blue_light
    output: blue_led
